import 'package:fast_shop/src/config/constants/Strings.dart';
import 'package:fast_shop/src/utils/widgets/Custom_myorder_container.dart';

List<Custommyordercontainer> myreturnlist = const [
  Custommyordercontainer(
    ctrinputHeight: 150,
    dod: '6 pm Today',
    imgpth: nikespts,
    name: 'Nike sports wear club Fleece',
    orderid: '678901',
    ordpe: '12\$',
    typser: "Order Delivered",
    status: 'Delivered at',
    bttxt: "Give Feeback",
    nxtsvr: "Return",
    ntst: "/rres",
    opt: true,
  ),
  Custommyordercontainer(
    ctrinputHeight: 150,
    dod: '6 pm Today',
    imgpth: bgbl,
    name: 'Nike Academy team Sports bag',
    orderid: '678901',
    ordpe: '90\$',
    typser: "Order Delivered",
    status: 'Delivered at',
    bttxt: "Give Feeback",
    nxtsvr: "Return",
    ntst: "/rres",
    opt: true,
  ),
  Custommyordercontainer(
    ctrinputHeight: 150,
    dod: '6 pm Today',
    imgpth: aplwt,
    name: 'Smart watch series 4 Sports',
    orderid: '678901',
    ordpe: '22\$',
    typser: "Order Delivered",
    status: 'Delivered at',
    bttxt: "Give Feeback",
    nxtsvr: "Return",
    ntst: "/rres",
    opt: true,
  ),
];
