// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDww0-0QhnyXgraD0Z-D5Y14rRxXKe54-o',
    appId: '1:1068771384190:web:6e43e8fecab21acb4c712f',
    messagingSenderId: '1068771384190',
    projectId: 'fastshop-806ad',
    authDomain: 'fastshop-806ad.firebaseapp.com',
    storageBucket: 'fastshop-806ad.appspot.com',
    measurementId: 'G-PEMC0P1K44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQd1KeBvOXg29Se0KJcGd3MPLanIzfkM',
    appId: '1:1068771384190:android:abd20d6617c5eb864c712f',
    messagingSenderId: '1068771384190',
    projectId: 'fastshop-806ad',
    storageBucket: 'fastshop-806ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioJN97rTCPEtH6XmFdx5hZ3HWh8KIJkg',
    appId: '1:1068771384190:ios:c957584e805d76fe4c712f',
    messagingSenderId: '1068771384190',
    projectId: 'fastshop-806ad',
    storageBucket: 'fastshop-806ad.appspot.com',
    iosClientId: '1068771384190-1dcu251bllgb0630m2rsiu8mqvc88fcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDioJN97rTCPEtH6XmFdx5hZ3HWh8KIJkg',
    appId: '1:1068771384190:ios:c957584e805d76fe4c712f',
    messagingSenderId: '1068771384190',
    projectId: 'fastshop-806ad',
    storageBucket: 'fastshop-806ad.appspot.com',
    iosClientId: '1068771384190-1dcu251bllgb0630m2rsiu8mqvc88fcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastShop',
  );
}
